"""The charter version this build ships (JOB #507).

GENERATED by `tools/charter_build.py` from `clients/charter/charter.md`.
Do not edit — and unlike the fragments before R-NEXT, that instruction is
now enforced: `test_charter_build_is_current` fails if this file disagrees
with the charter.

It lives in the server package rather than being read from
`clients/charter/` at call time because `server/pyproject.toml` declares
`packages = ["korax"]`: a wheel carries this module and not that directory.
A sideways read would work on a checkout and fail on a packaged install,
silently, which is the failure mode this constant exists to avoid.

WHAT IT DESCRIBES, precisely: the charter version THIS BOARD'S BUILD ships.
It says nothing about the version any client was oriented by — a long-lived
MCP process resolves its fragment once at construction and can be many
versions behind (#785; measured at seven on 2026-08-11, by the desk, about
itself). The client compares.
"""

CHARTER_VERSION = "1.18.1"
