#!/usr/bin/env python3
"""Derive everything that can be derived from `clients/charter/charter.md`.

JOB #507 needs the charter version inside the SERVER package, because
`server/pyproject.toml` declares `packages = ["korax"]` — a server wheel
carries `korax/` and nothing else, so a reduction reaching sideways into
`clients/charter/` works on a checkout **by accident** and breaks silently on
the first packaged install. That is #713's `conventions.md` lesson, and the
reduction whose purpose is refusing stale orientation is the worst possible
place to rebuild it.

WHAT THIS DOES AND DOES NOT DERIVE, because #702 is about a directory that
claims to be generated and is not:

  - DERIVED: the version string, in all four places it appears.
  - NOT DERIVED, and never will be: the fragment BODIES. The header now
    SAYS so rather than reading `do not edit by hand` over prose no script
    writes (#702) — a file that misdescribes itself teaches every reader
    the wrong thing about which half is safe to touch. They are ~150 and
    ~200 word compressions of a 262-line charter — editorial work, not a
    transformation. A script cannot write them and should not pretend to.

So `clients/charter/README.md`'s claim becomes true for the half a machine
can own, and honest about the half it cannot. The version was the part that
actually drifted: it went unenforced through six bumps while the README sat
at 1.0.0 and the charter reached 1.6.0.

Run it, or let CI run it — `test_charter_build_is_current` fails if the tree
disagrees with what this produces, which is what makes "generated" mean
something rather than describe an intention.

    python tools/charter_build.py            # write
    python tools/charter_build.py --check    # exit 1 if anything is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CHARTER = REPO / "clients" / "charter" / "charter.md"
README = REPO / "clients" / "charter" / "README.md"
FRAGMENTS = REPO / "clients" / "charter" / "fragments"
SERVER_CONSTANT = REPO / "server" / "korax" / "_charter.py"

_VERSION = re.compile(r"<!-- korax-charter VERSION ([0-9]+\.[0-9]+\.[0-9]+)")
_FRAGMENT_HEADER = re.compile(r"^<!-- generated from charter\.md v[0-9.]+ [^>]*-->")
_README_VERSION = re.compile(r"^VERSION [0-9]+\.[0-9]+\.[0-9]+$", re.MULTILINE)

CONSTANT_TEMPLATE = '''"""The charter version this build ships (JOB #507).

GENERATED by `tools/charter_build.py` from `clients/charter/charter.md`.
Do not edit — and unlike the fragments before R-NEXT, that instruction is
now enforced: `test_charter_build_is_current` fails if this file disagrees
with the charter.

It lives in the server package rather than being read from
`clients/charter/` at call time because `server/pyproject.toml` declares
`packages = ["korax"]`: a wheel carries this module and not that directory.
A sideways read would work on a checkout and fail on a packaged install,
silently, which is the failure mode this constant exists to avoid.

WHAT IT DESCRIBES, precisely: the charter version THIS BOARD'S BUILD ships.
It says nothing about the version any client was oriented by — a long-lived
MCP process resolves its fragment once at construction and can be many
versions behind (#785; measured at seven on 2026-08-11, by the desk, about
itself). The client compares.
"""

CHARTER_VERSION = "{version}"
'''


def charter_version(text: str) -> str:
    match = _VERSION.search(text)
    if match is None:
        raise SystemExit(
            f"{CHARTER}: no `<!-- korax-charter VERSION x.y.z -->` header; "
            "that comment is the single source and everything else derives "
            "from it"
        )
    return match.group(1)


def render(version: str) -> dict[Path, str]:
    """Every derived artifact, as {path: wanted contents}."""
    wanted: dict[Path, str] = {
        SERVER_CONSTANT: CONSTANT_TEMPLATE.format(version=version)
    }

    readme = README.read_text(encoding="utf-8")
    wanted[README] = _README_VERSION.sub(f"VERSION {version}", readme, count=1)

    for fragment in sorted(FRAGMENTS.glob("*.md")):
        body = fragment.read_text(encoding="utf-8")
        if not _FRAGMENT_HEADER.match(body):
            raise SystemExit(
                f"{fragment}: missing the `<!-- generated from charter.md "
                "vX.Y.Z — … -->` first line. The header is "
                "how a reader knows what this was derived from; a fragment "
                "without one is unversioned prose."
            )
        wanted[fragment] = _FRAGMENT_HEADER.sub(
            f"<!-- generated from charter.md v{version} — version line only; the body "
            f"below is editorial, not derived (#702). -->",
            body, count=1,
        )
    return wanted


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if anything is stale")
    args = parser.parse_args(argv)

    version = charter_version(CHARTER.read_text(encoding="utf-8"))
    wanted = render(version)

    stale = [
        path for path, contents in wanted.items()
        if not path.exists() or path.read_text(encoding="utf-8") != contents
    ]
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(REPO)}", file=sys.stderr)
        if stale:
            print(f"charter is v{version}; run `python tools/charter_build.py`",
                  file=sys.stderr)
        return 1 if stale else 0

    for path in stale:
        path.write_text(wanted[path], encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    if not stale:
        print(f"already current at v{version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
